
import {
  TbUsers,
  TbAlertTriangle,
  TbUserCheck,
  TbTrendingUp,
  TbUserPlus,
} from "react-icons/tb";

export const stats = [
  {
    icon: TbUsers,
    iconClass: "total",
    value: "214",
    title: "TOTAL BOOKINGS",
    footer: "+16 this month",
    bgColor: "#DDF5F0",
    iconColor: "#0F766E",
    footerClass: "metric-growth text-success",
  },
  {
    icon: TbAlertTriangle,
    iconClass: "pending",
    value: "28",
    title: "PENDING",
    footer: "Needs action",
     bgColor: "#FEF3D7",
    iconColor: "#D97706",
    footerClass: "metric-alert",
  },
  {
    icon: TbUserCheck,
    iconClass: "confirmed",
    value: "₹5,18,200",
    title: "CONFIRMED",
    footer: "+8.7% last month",
    bgColor: "#E7F4EE",
    iconColor: "#14B8A6",
    footerClass: "metric-growth text-success",
  },
  {
    icon: TbTrendingUp,
    iconClass: "revenue",
    value: "₹8.4L",
    title: "REVENUE",
    footer: "+24% vs last mo",
    bgColor: "#FDE8E8",
    iconColor: "#EF4444",
    footerClass: "metric-growth text-success",
  },
  {
    icon: TbUserPlus,
    iconClass: "upcoming",
    value: "38",
    title: "UPCOMING",
    footer: "+12% vs last month",
     bgColor: "#E8F0FE",
    iconColor: "#2563EB",
    footerClass: "metric-growth text-success",
  },
];

export const activeBookings = [
  {
    id: "#BK-2026-422",
    customer: "Anjali Sharma",
    eventType: "Wedding",
    date: "Jul 12, 2026",
    amount: "₹2,85,856",
    status1: { text: "Confirmed", color: "success-light" },
    status2: { text: "Partial Paid", color: "warning-light" },
  },

  {
    id: "#BK-2026-421",
    customer: "Anand Corp",
    eventType: "Corporate",
    date: "Jun 28, 2026",
    amount: "₹1,09,428",
    status1: { text: "In Progress", color: "success-light" },
    status2: { text: "Paid", color: "success-light" },
  },

  {
    id: "#BK-2026-420",
    customer: "Meera Joshi",
    eventType: "Birthday",
    date: "Jun 25, 2026",
    amount: "₹32,488",
    status1: { text: "Upcoming", color: "primary-light" },
    status2: { text: "Overdue", color: "danger-light" },
  },

  {
    id: "#BK-2026-419",
    customer: "Dev Malhotra",
    eventType: "Religious",
    date: "Aug 03, 2026",
    amount: "₹21,240",
    status1: { text: "Pending", color: "warning-light" },
    status2: { text: "Pending", color: "warning-light" },
  },
];

export const bookings = [
  {
    bookingId: "#QT-2026-088",
    description: "Upto 500 guests · premium",
    initials: "AS",
    avatarClass: "green",
    customer: "Anjali Sharma",
    email: "anjali@gmail.com",
    eventType: "Wedding",
    eventClass: "pink",
    amount: "₹2,40,856",
    date: "Jul 12, 2026",
    venue: "Grand Ballroom",
    status1: { text: "Confirmed", color: "success-pill" },
    status: "Confirmed",
    statusClass: "success-pill",
  },

  {
    bookingId: "#QT-2026-087",
    description: "Upto 200 guests · premium",
    initials: "RP",
    avatarClass: "red",
    customer: "Nikhil Kumar",
    email: "nikhil@work.com",
    eventType: "Corporate",
    eventClass: "blue",
    amount: "₹2,50,428",
    date: "Jun 28, 2026",
    venue: "Convention Hall",
     status1: { text: "Accepted", color: "purple-pill" },
    status: "Accepted",
    statusClass: "purple-pill",
  },

  {
    bookingId: "#QT-2026-086",
    description: "Full decor + entertainment",
    initials: "MG",
    avatarClass: "orange",
    customer: "Meena Gupta",
    email: "meena@yahoo.com",
    eventType: "Birthday",
    eventClass: "pink",
    amount: "₹60,488",
    date: "Jun 25, 2026",
    venue: "Garden Venue",
    status1: { text: "In Progress", color: "teal-pill" },
    status: "In Progress",
    statusClass: "teal-pill",
  },

  {
    bookingId: "#QT-2026-085",
    description: "AV setup",
    initials: "RP",
    avatarClass: "blue",
    customer: "Rohan Patel",
    email: "rohan@hotmail.com",
    eventType: "Religious",
    eventClass: "green",
    amount: "₹4,12,640",
    date: "Aug 03, 2026",
    venue: "Community Hall",
    status1: { text: "Pending", color: "orange-pill" },
    status: "Pending",
    statusClass: "orange-pill",
  },
  {
  bookingId: "#QT-2026-086",
  description: "Upto 350 guests · premium",
  initials: "PM",
  avatarClass: "blue",
  customer: "Priya Mehta",
  email: "priya.mehta@gmail.com",
  eventType: "Engagement",
  eventClass: "purple",
  amount: "₹1,85,750",
  date: "Aug 05, 2026",
  venue: "Royal Banquet",
   status1: { text: "Pending", color: "orange-pill" },
  status: "Pending",
  statusClass: "warning-pill",
},

{
  bookingId: "#QT-2026-085",
  description: "Upto 150 guests · standard",
  initials: "VK",
  avatarClass: "orange",
  customer: "Vikram Khanna",
  email: "vikram.khanna@yahoo.com",
  eventType: "Birthday",
  eventClass: "yellow",
  amount: "₹95,320",
  date: "Sep 18, 2026",
  venue: "Garden Terrace",
  status1: { text: "Rejected", color: "danger-pill" },
  status: "Rejected",
  statusClass: "danger-pill",
}
];